name: Tests

on: [push]

jobs:
  build:
    name: "Unit Tests for python ${{ matrix.python }} on ${{ matrix.os }}"

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python: ["3.8", "3.9", "3.10"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.1.8
          poetry config virtualenvs.create false
          poetry install --no-interaction -E "yaml"

      - name: Run Unit Tests
        run: |
          pytest --doctest-modules $(find src -type f -name "*.py" | sort | xargs)

      # - name: Run Unit Tests
      #   run: |
      #     pytest --doctest-modules --cov=src/ --cov-report=term-missing --cov-report=xml src/ tests/

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1
      #   with:
      #     file: ./coverage.xml
      #     fail_ci_if_error: true
